// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/covest.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cov_est
NumericMatrix cov_est(arma::mat x, NumericVector z, double znew, double h, arma::mat cest_old, double sumK_old, arma::mat mx);
RcppExport SEXP _covest_cov_est(SEXP xSEXP, SEXP zSEXP, SEXP znewSEXP, SEXP hSEXP, SEXP cest_oldSEXP, SEXP sumK_oldSEXP, SEXP mxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type znew(znewSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type cest_old(cest_oldSEXP);
    Rcpp::traits::input_parameter< double >::type sumK_old(sumK_oldSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mx(mxSEXP);
    rcpp_result_gen = Rcpp::wrap(cov_est(x, z, znew, h, cest_old, sumK_old, mx));
    return rcpp_result_gen;
END_RCPP
}
// mean_est
NumericMatrix mean_est(arma::mat x, NumericVector z, double znew, double h, NumericVector mean_old, double sumK_old);
RcppExport SEXP _covest_mean_est(SEXP xSEXP, SEXP zSEXP, SEXP znewSEXP, SEXP hSEXP, SEXP mean_oldSEXP, SEXP sumK_oldSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type znew(znewSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mean_old(mean_oldSEXP);
    Rcpp::traits::input_parameter< double >::type sumK_old(sumK_oldSEXP);
    rcpp_result_gen = Rcpp::wrap(mean_est(x, z, znew, h, mean_old, sumK_old));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_covest_cov_est", (DL_FUNC) &_covest_cov_est, 7},
    {"_covest_mean_est", (DL_FUNC) &_covest_mean_est, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_covest(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
